name: Build and Release

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev ninja-build

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Install
        run: cmake --install build

      - name: Package
        run: cd build && cpack -G DEB

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: munition-deb
          path: build/*.deb

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
